services:
    broker:
        image: apache/kafka:3.7.0
        hostname: kafka
        container_name: kafka
        ports:
            - '9092:9092'
        environment:
            - KAFKA_PROCESS_ROLES=broker,controller
            - KAFKA_NODE_ID=0
            - KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
            - KAFKA_LISTENERS=CONTROLLER://:9093,PLAINTEXT://:9092
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
            - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
            - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
            - AUTO_CREATE_TOPICS=false