external:
    services:
        hipsum:
            base-url: https://hipsum.co/api/
            paras-parameter-value: 1
            full-url: ${external.services.hipsum.base-url}?type=hipster-centric&paras=${external.services.hipsum.paras-parameter-value}
        kafka:
            topic: words.processed
server:
    port: 8090
spring:
    application:
        name: processing-app
    kafka:
        producer:
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer